//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class MaterialEntity
    {
        private int _idx;
        private string _eb001;
        private string _eb002;
        private string _eb003;
        private int? _eb004;
        private DateTime? _eb005;
        private decimal? _eb006;
        private decimal? _eb007;
        private decimal? _eb008;
        private decimal? _eb009;
        private decimal? _eb010;
        private decimal? _eb011;
        private decimal? _eb012;
        private decimal? _eb013;
        private decimal? _eb014;
        private decimal? _eb015;
        private decimal? _eb016;
        private decimal? _eb017;
        private decimal? _eb018;
        private decimal? _eb019;
        private decimal? _eb020;
        private decimal? _eb021;
        private decimal? _eb022;
        private decimal? _eb023;
        private decimal? _eb024;
        private decimal? _eb025;
        private decimal? _eb026;
        private decimal? _eb027;
        private decimal? _eb028;
        private decimal? _eb029;
        private decimal? _eb030;
        private decimal? _eb031;
        private decimal? _eb032;
        private decimal? _eb033;
        private decimal? _eb034;
        private decimal? _eb035;
        private decimal? _eb036;
        private decimal? _eb037;
        private decimal? _eb038;
        private decimal? _eb039;
        private decimal? _eb040;
        private decimal? _eb041;
        private decimal? _eb042;
        private decimal? _eb043;
        private decimal? _eb044;
        private string _eb045;
        private string _eb046;
        private string _eb047;
        private string _eb048;
        private string _eb049;
        private string _eb050;
        /// <summary>
        /// 
        /// </summary>
        public int idx
        {
            set
            {
                _idx = value;
            }
            get
            {
                return _idx;
            }
        }
        /// <summary>
        /// 产品名称
        /// </summary>
        public string EB001
        {
            set
            {
                _eb001 = value;
            }
            get
            {
                return _eb001;
            }
        }
        /// <summary>
        /// 流水号
        /// </summary>
        public string EB002
        {
            set
            {
                _eb002 = value;
            }
            get
            {
                return _eb002;
            }
        }
        /// <summary>
        /// 货号
        /// </summary>
        public string EB003
        {
            set
            {
                _eb003 = value;
            }
            get
            {
                return _eb003;
            }
        }
        /// <summary>
        /// 产品数量
        /// </summary>
        public int? EB004
        {
            set
            {
                _eb004 = value;
            }
            get
            {
                return _eb004;
            }
        }
        /// <summary>
        /// 交货日期
        /// </summary>
        public DateTime? EB005
        {
            set
            {
                _eb005 = value;
            }
            get
            {
                return _eb005;
            }
        }
        /// <summary>
        /// R-059每套成本(胶合板)
        /// </summary>
        public decimal? EB006
        {
            set
            {
                _eb006 = value;
            }
            get
            {
                return _eb006;
            }
        }
        /// <summary>
        /// R-241原每套成本(胶合板)
        /// </summary>
        public decimal? EB007
        {
            set
            {
                _eb007 = value;
            }
            get
            {
                return _eb007;
            }
        }
        /// <summary>
        /// R-241现每套成本(胶合板)
        /// </summary>
        public decimal? EB008
        {
            set
            {
                _eb008 = value;
            }
            get
            {
                return _eb008;
            }
        }
        /// <summary>
        /// R-059原每套成本(密度板)
        /// </summary>
        public decimal? EB009
        {
            set
            {
                _eb009 = value;
            }
            get
            {
                return _eb009;
            }
        }
        /// <summary>
        /// R-241原每套成本(密度板)
        /// </summary>
        public decimal? EB010
        {
            set
            {
                _eb010 = value;
            }
            get
            {
                return _eb010;
            }
        }
        /// <summary>
        /// R-241现每套成本(密度板)
        /// </summary>
        public decimal? EB011
        {
            set
            {
                _eb011 = value;
            }
            get
            {
                return _eb011;
            }
        }
        /// <summary>
        /// R-059原每套成本(木材)
        /// </summary>
        public decimal? EB012
        {
            set
            {
                _eb012 = value;
            }
            get
            {
                return _eb012;
            }
        }
        /// <summary>
        /// R-241原每套成本(木材)
        /// </summary>
        public decimal? EB013
        {
            set
            {
                _eb013 = value;
            }
            get
            {
                return _eb013;
            }
        }
        /// <summary>
        /// R-241现每套成本(木材)
        /// </summary>
        public decimal? EB014
        {
            set
            {
                _eb014 = value;
            }
            get
            {
                return _eb014;
            }
        }
        /// <summary>
        /// R-059原每套成本(车木件)
        /// </summary>
        public decimal? EB015
        {
            set
            {
                _eb015 = value;
            }
            get
            {
                return _eb015;
            }
        }
        /// <summary>
        /// R-241原每套成本(车木件)
        /// </summary>
        public decimal? EB016
        {
            set
            {
                _eb016 = value;
            }
            get
            {
                return _eb016;
            }
        }
        /// <summary>
        /// R-241现每套成本(车木件)
        /// </summary>
        public decimal? EB017
        {
            set
            {
                _eb017 = value;
            }
            get
            {
                return _eb017;
            }
        }
        /// <summary>
        /// R-059原每套成本(铁件)
        /// </summary>
        public decimal? EB018
        {
            set
            {
                _eb018 = value;
            }
            get
            {
                return _eb018;
            }
        }
        /// <summary>
        /// R-241原每套成本(铁件)
        /// </summary>
        public decimal? EB019
        {
            set
            {
                _eb019 = value;
            }
            get
            {
                return _eb019;
            }
        }
        /// <summary>
        /// R-241现每套成本(铁件)
        /// </summary>
        public decimal? EB020
        {
            set
            {
                _eb020 = value;
            }
            get
            {
                return _eb020;
            }
        }
        /// <summary>
        /// R-059原每套成本(塑料件)
        /// </summary>
        public decimal? EB021
        {
            set
            {
                _eb021 = value;
            }
            get
            {
                return _eb021;
            }
        }
        /// <summary>
        /// R-241原每套成本(塑料件)
        /// </summary>
        public decimal? EB022
        {
            set
            {
                _eb022 = value;
            }
            get
            {
                return _eb022;
            }
        }
        /// <summary>
        /// R-241现每套成本(塑料件)
        /// </summary>
        public decimal? EB023
        {
            set
            {
                _eb023 = value;
            }
            get
            {
                return _eb023;
            }
        }
        /// <summary>
        /// R-509每套成本(其他材料)
        /// </summary>
        public decimal? EB024
        {
            set
            {
                _eb024 = value;
            }
            get
            {
                return _eb024;
            }
        }
        /// <summary>
        /// R-241原每套成本(其他材料)
        /// </summary>
        public decimal? EB025
        {
            set
            {
                _eb025 = value;
            }
            get
            {
                return _eb025;
            }
        }
        /// <summary>
        /// R-241现每套成本(其他材料)
        /// </summary>
        public decimal? EB026
        {
            set
            {
                _eb026 = value;
            }
            get
            {
                return _eb026;
            }
        }
        /// <summary>
        /// R-509每套成本(包装辅料)
        /// </summary>
        public decimal? EB027
        {
            set
            {
                _eb027 = value;
            }
            get
            {
                return _eb027;
            }
        }
        /// <summary>
        /// R-241原每套成本(包装辅料)
        /// </summary>
        public decimal? EB028
        {
            set
            {
                _eb028 = value;
            }
            get
            {
                return _eb028;
            }
        }
        /// <summary>
        /// R-241现每套成本(包装辅料)
        /// </summary>
        public decimal? EB029
        {
            set
            {
                _eb029 = value;
            }
            get
            {
                return _eb029;
            }
        }
        /// <summary>
        /// R-509每套成本(纸箱（中包、内盒、外箱）)
        /// </summary>
        public decimal? EB030
        {
            set
            {
                _eb030 = value;
            }
            get
            {
                return _eb030;
            }
        }
        /// <summary>
        /// R-241原每套成本(纸箱（中包、内盒、外箱）)
        /// </summary>
        public decimal? EB031
        {
            set
            {
                _eb031 = value;
            }
            get
            {
                return _eb031;
            }
        }
        /// <summary>
        /// R-241现每套成本(纸箱（中包、内盒、外箱）)
        /// </summary>
        public decimal? EB032
        {
            set
            {
                _eb032 = value;
            }
            get
            {
                return _eb032;
            }
        }
        /// <summary>
        /// R-509每套成本(彩盒)
        /// </summary>
        public decimal? EB033
        {
            set
            {
                _eb033 = value;
            }
            get
            {
                return _eb033;
            }
        }
        /// <summary>
        /// R-241原每套成本(彩盒)
        /// </summary>
        public decimal? EB034
        {
            set
            {
                _eb034 = value;
            }
            get
            {
                return _eb034;
            }
        }
        /// <summary>
        /// R-241现每套成本(彩盒)
        /// </summary>
        public decimal? EB035
        {
            set
            {
                _eb035 = value;
            }
            get
            {
                return _eb035;
            }
        }
        /// <summary>
        /// R-509每套成本(委外加工)
        /// </summary>
        public decimal? EB036
        {
            set
            {
                _eb036 = value;
            }
            get
            {
                return _eb036;
            }
        }
        /// <summary>
        /// R-241原每套成本(委外加工)
        /// </summary>
        public decimal? EB037
        {
            set
            {
                _eb037 = value;
            }
            get
            {
                return _eb037;
            }
        }
        /// <summary>
        /// R-241现每套成本(委外加工)
        /// </summary>
        public decimal? EB038
        {
            set
            {
                _eb038 = value;
            }
            get
            {
                return _eb038;
            }
        }
        /// <summary>
        /// R-509每套成本滚漆油漆（厂内滚漆油漆、厂外滚漆油漆+厂外滚漆工资）
        /// </summary>
        public decimal? EB039
        {
            set
            {
                _eb039 = value;
            }
            get
            {
                return _eb039;
            }
        }
        /// <summary>
        /// R-241原每套成本滚漆油漆（厂内滚漆油漆、厂外滚漆油漆+厂外滚漆工资）
        /// </summary>
        public decimal? EB040
        {
            set
            {
                _eb040 = value;
            }
            get
            {
                return _eb040;
            }
        }
        /// <summary>
        /// R-241现每套成本滚漆油漆（厂内滚漆油漆、厂外滚漆油漆+厂外滚漆工资）
        /// </summary>
        public decimal? EB041
        {
            set
            {
                _eb041 = value;
            }
            get
            {
                return _eb041;
            }
        }
        /// <summary>
        /// R-509每套成本喷漆油漆
        /// </summary>
        public decimal? EB042
        {
            set
            {
                _eb042 = value;
            }
            get
            {
                return _eb042;
            }
        }
        /// <summary>
        /// R-241原每套成本喷漆油漆
        /// </summary>
        public decimal? EB043
        {
            set
            {
                _eb043 = value;
            }
            get
            {
                return _eb043;
            }
        }
        /// <summary>
        /// R-241现每套成本喷漆油漆
        /// </summary>
        public decimal? EB044
        {
            set
            {
                _eb044 = value;
            }
            get
            {
                return _eb044;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EB045
        {
            set
            {
                _eb045 = value;
            }
            get
            {
                return _eb045;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EB046
        {
            set
            {
                _eb046 = value;
            }
            get
            {
                return _eb046;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EB047
        {
            set
            {
                _eb047 = value;
            }
            get
            {
                return _eb047;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EB048
        {
            set
            {
                _eb048 = value;
            }
            get
            {
                return _eb048;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EB049
        {
            set
            {
                _eb049 = value;
            }
            get
            {
                return _eb049;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EB050
        {
            set
            {
                _eb050 = value;
            }
            get
            {
                return _eb050;
            }
        }

    }
}
