//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulaolaoLibrary
{
    using System;
    
    
    public sealed class WagesEntity
    {
        private int _idx;
        private string _ec001;
        private string _ec002;
        private string _ec003;
        private int? _ec004;
        private DateTime? _ec005;
        private decimal? _ec006;
        private decimal? _ec007;
        private decimal? _ec008;
        private decimal? _ec009;
        private decimal? _ec010;
        private decimal? _ec011;
        private decimal? _ec012;
        private decimal? _ec013;
        private decimal? _ec014;
        private decimal? _ec015;
        private decimal? _ec016;
        private decimal? _ec017;
        private decimal? _ec018;
        private decimal? _ec019;
        private decimal? _ec020;
        private decimal? _ec021;
        private decimal? _ec022;
        private decimal? _ec023;
        private decimal? _ec024;
        private decimal? _ec025;
        private decimal? _ec026;
        private decimal? _ec027;
        private decimal? _ec028;
        private decimal? _ec029;
        private decimal? _ec030;
        private decimal? _ec031;
        private decimal? _ec032;
        /// <summary>
        /// 
        /// </summary>
        public int idx
        {
            set
            {
                _idx = value;
            }
            get
            {
                return _idx;
            }
        }
        /// <summary>
        /// 产品名称
        /// </summary>
        public string EC001
        {
            set
            {
                _ec001 = value;
            }
            get
            {
                return _ec001;
            }
        }
        /// <summary>
        /// 流水号
        /// </summary>
        public string EC002
        {
            set
            {
                _ec002 = value;
            }
            get
            {
                return _ec002;
            }
        }
        /// <summary>
        /// 货号
        /// </summary>
        public string EC003
        {
            set
            {
                _ec003 = value;
            }
            get
            {
                return _ec003;
            }
        }
        /// <summary>
        /// 产品数量
        /// </summary>
        public int? EC004
        {
            set
            {
                _ec004 = value;
            }
            get
            {
                return _ec004;
            }
        }
        /// <summary>
        /// 交货日期
        /// </summary>
        public DateTime? EC005
        {
            set
            {
                _ec005 = value;
            }
            get
            {
                return _ec005;
            }
        }
        /// <summary>
        /// R-059原每套成本(前道工资)
        /// </summary>
        public decimal? EC006
        {
            set
            {
                _ec006 = value;
            }
            get
            {
                return _ec006;
            }
        }
        /// <summary>
        /// R-317原每套成本(前道工资)
        /// </summary>
        public decimal? EC007
        {
            set
            {
                _ec007 = value;
            }
            get
            {
                return _ec007;
            }
        }
        /// <summary>
        /// R-317现每套成本(前道工资)
        /// </summary>
        public decimal? EC008
        {
            set
            {
                _ec008 = value;
            }
            get
            {
                return _ec008;
            }
        }
        /// <summary>
        /// R-059原每套成本(后道工资)
        /// </summary>
        public decimal? EC009
        {
            set
            {
                _ec009 = value;
            }
            get
            {
                return _ec009;
            }
        }
        /// <summary>
        /// R-317原每套成本(后道工资)
        /// </summary>
        public decimal? EC010
        {
            set
            {
                _ec010 = value;
            }
            get
            {
                return _ec010;
            }
        }
        /// <summary>
        /// R-317现每套成本(后道工资)
        /// </summary>
        public decimal? EC011
        {
            set
            {
                _ec011 = value;
            }
            get
            {
                return _ec011;
            }
        }
        /// <summary>
        /// R-059原每套成本(检验)
        /// </summary>
        public decimal? EC012
        {
            set
            {
                _ec012 = value;
            }
            get
            {
                return _ec012;
            }
        }
        /// <summary>
        /// R-317原每套成本(检验)
        /// </summary>
        public decimal? EC013
        {
            set
            {
                _ec013 = value;
            }
            get
            {
                return _ec013;
            }
        }
        /// <summary>
        /// R-317现每套成本(检验)
        /// </summary>
        public decimal? EC014
        {
            set
            {
                _ec014 = value;
            }
            get
            {
                return _ec014;
            }
        }
        /// <summary>
        /// R-059原每套成本(包装)
        /// </summary>
        public decimal? EC015
        {
            set
            {
                _ec015 = value;
            }
            get
            {
                return _ec015;
            }
        }
        /// <summary>
        /// R-317原每套成本(包装)
        /// </summary>
        public decimal? EC016
        {
            set
            {
                _ec016 = value;
            }
            get
            {
                return _ec016;
            }
        }
        /// <summary>
        /// R-317现每套成本(包装)
        /// </summary>
        public decimal? EC017
        {
            set
            {
                _ec017 = value;
            }
            get
            {
                return _ec017;
            }
        }
        /// <summary>
        /// R-059原每套成本(雕刻)
        /// </summary>
        public decimal? EC018
        {
            set
            {
                _ec018 = value;
            }
            get
            {
                return _ec018;
            }
        }
        /// <summary>
        /// R-241原每套成本(雕刻)
        /// </summary>
        public decimal? EC019
        {
            set
            {
                _ec019 = value;
            }
            get
            {
                return _ec019;
            }
        }
        /// <summary>
        /// R-241现每套成本(雕刻)
        /// </summary>
        public decimal? EC020
        {
            set
            {
                _ec020 = value;
            }
            get
            {
                return _ec020;
            }
        }
        /// <summary>
        /// R-059原每套成本热转印
        /// </summary>
        public decimal? EC021
        {
            set
            {
                _ec021 = value;
            }
            get
            {
                return _ec021;
            }
        }
        /// <summary>
        /// R-241原每套成本(热转印)
        /// </summary>
        public decimal? EC022
        {
            set
            {
                _ec022 = value;
            }
            get
            {
                return _ec022;
            }
        }
        /// <summary>
        /// R-241现每套成本(热转印)
        /// </summary>
        public decimal? EC023
        {
            set
            {
                _ec023 = value;
            }
            get
            {
                return _ec023;
            }
        }
        /// <summary>
        /// R-059原每套成本滚漆
        /// </summary>
        public decimal? EC024
        {
            set
            {
                _ec024 = value;
            }
            get
            {
                return _ec024;
            }
        }
        /// <summary>
        /// R-241原每套成本滚漆
        /// </summary>
        public decimal? EC025
        {
            set
            {
                _ec025 = value;
            }
            get
            {
                return _ec025;
            }
        }
        /// <summary>
        /// R-241现每套成本滚漆
        /// </summary>
        public decimal? EC026
        {
            set
            {
                _ec026 = value;
            }
            get
            {
                return _ec026;
            }
        }
        /// <summary>
        /// R-059原每套成本喷漆
        /// </summary>
        public decimal? EC027
        {
            set
            {
                _ec027 = value;
            }
            get
            {
                return _ec027;
            }
        }
        /// <summary>
        /// R-241原每套成本喷漆
        /// </summary>
        public decimal? EC028
        {
            set
            {
                _ec028 = value;
            }
            get
            {
                return _ec028;
            }
        }
        /// <summary>
        /// R-241现每套成本喷漆
        /// </summary>
        public decimal? EC029
        {
            set
            {
                _ec029 = value;
            }
            get
            {
                return _ec029;
            }
        }
        /// <summary>
        /// R-059原每套成本承揽
        /// </summary>
        public decimal? EC030
        {
            set
            {
                _ec030 = value;
            }
            get
            {
                return _ec030;
            }
        }
        /// <summary>
        /// R-241原每套成本承揽
        /// </summary>
        public decimal? EC031
        {
            set
            {
                _ec031 = value;
            }
            get
            {
                return _ec031;
            }
        }
        /// <summary>
        /// R-241现每套成本承揽
        /// </summary>
        public decimal? EC032
        {
            set
            {
                _ec032 = value;
            }
            get
            {
                return _ec032;
            }
        }
    }
}
